
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Nov 28 14:00:40 EST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRLIT = 2;
  public static final int rw_WHILE = 4;
  public static final int rw_FLOAT = 3;
  public static final int rw_BOOL = 5;
  public static final int LBRACKET = 6;
  public static final int rw_IF = 7;
  public static final int SLASH = 45;
  public static final int rw_CONTINUE = 8;
  public static final int rw_FALSE = 9;
  public static final int LPAREN = 10;
  public static final int SEMI = 11;
  public static final int rw_PRINT = 12;
  public static final int rw_TRUE = 13;
  public static final int MINUS = 48;
  public static final int RPAREN = 14;
  public static final int NOT = 15;
  public static final int INTLIT = 16;
  public static final int rw_VOID = 17;
  public static final int LT = 18;
  public static final int rw_CONST = 19;
  public static final int COMMA = 20;
  public static final int INC = 21;
  public static final int rw_ELSE = 22;
  public static final int GEQ = 23;
  public static final int PLUS = 47;
  public static final int rw_READ = 24;
  public static final int rw_INT = 25;
  public static final int EOF = 0;
  public static final int rw_FOR = 50;
  public static final int RBRACKET = 26;
  public static final int error = 1;
  public static final int COR = 27;
  public static final int rw_CLASS = 28;
  public static final int rw_RETURN = 29;
  public static final int EQ = 30;
  public static final int FLOATLIT = 31;
  public static final int ASG = 32;
  public static final int TIMES = 46;
  public static final int CHARLIT = 33;
  public static final int COLON = 34;
  public static final int LBRACE = 35;
  public static final int rw_CHAR = 36;
  public static final int CAND = 38;
  public static final int RBRACE = 37;
  public static final int LEQ = 39;
  public static final int rw_BREAK = 40;
  public static final int DEC = 41;
  public static final int rw_ENDIF = 49;
  public static final int GT = 42;
  public static final int NOTEQ = 43;
  public static final int IDENTIFIER = 44;
}

