
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Nov 28 13:09:12 EST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 11;
  public static final int LBRACE = 8;
  public static final int ASG = 7;
  public static final int rw_BOOL = 13;
  public static final int rw_IF = 12;
  public static final int INTLIT = 3;
  public static final int SEMI = 4;
  public static final int PLUS = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RPAREN = 6;
  public static final int IDENTIFIER = 2;
  public static final int rw_PRINT = 14;
  public static final int rw_INT = 15;
  public static final int RBRACE = 9;
  public static final int LPAREN = 5;
}

